# Generated by Django 6.0.6 on 2026-06-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=50)),
                ("anio_publicacion", models.IntegerField()),
                ("disponible", models.BooleanField(default=True)),
            ],
        ),
    ]
